# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 04a1f59c67014a8692c0e1fa08bf8b7923a32846133bcbae569e9876891c148a6bc06c3c750c5d87d5c9ffe0b4905d890cccfe381073a66850128936b7ff8f7f

test:
  domain_name: example.com 
  secret_key_base: d2175f1fa62640d2cad7fd310e08bba804854603f7a8bba3046e914b767a6dc93b0420da8d9e037e8bbc5e31092bc2ddd87fe2ee461e4d17582d7cc0f0e36ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
